name: Setup Repo

on:
  workflow_dispatch:

jobs:
  sonar-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: python -m pip install --upgrade requests python-sonarqube-api PyGithub

      - name: Add SonarCloud project
        shell: bash
        run: |
          set -e

          python .github/workflows/add_repository_sonar_cloud.py \
            --repository-name ${{ github.event.repository.full_name }}
            --github-access-token ${{ github.token }} \
            --sonar-cloud-access-token ${{ secrets.SONAR_ACCESS_TOKEN }} \
            --sonar-cloud-organization "test-crispy-couscous" \
            --installation-id 28005684 \
            --sonar-cloud-quality-gate-id 70954
